language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - setup=basic
    - coverage=false

sudo: false

branches:
  except:
    - gh-pages
    - /analysis-.*/

before_install:
  - if [[ $coverage = 'false' ]]; then phpenv config-rm xdebug.ini || true; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build


install:
  - if [[ $setup = 'basic'  ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script:
  - if [[ $coverage = 'true' ]]; then composer test-cover; else composer test; fi

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

after_success:
  - if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

matrix:
  include:
    - php: 7.2
      env: coverage=true
    - php: 7.2
      env: setup=lowest
    - php: 7.2
      env: setup=stable

    - php: 7.3
      env: coverage=true
    - php: 7.3
      env: setup=lowest
    - php: 7.3
      env: setup=stable

    - php: nightly

  allow_failures:
    - php: nightly
